DATA-38 - Applying some initial changes.
proversity-org/edx-analytics-exporter pull request #1
Opened 2019-07-20 00:50 UTC by Squirrel18

## Description:

This PR applies some changes in order to run the edx-analytics-exporter pipeline.

Changes:
- Removing support for encrypted files.
- Removing user and password for mongoexport command call.

2019-07-29 23:05 UTC, andrey-canon requested changes

2019-07-29 23:05 UTC, andrey-canon commented on exporter/tasks.py
> +    Initially the mongoexport command take the --username and --password parameters,
grammatical error, it's `takes`

2019-07-29 23:05 UTC, andrey-canon commented on exporter/tasks.py
> +            # we don't have data related to the previous run, so
grammatical error, it's 'related data'

2019-07-29 23:05 UTC, andrey-canon commented on exporter/tasks.py
> +            # this always raise a FatalTaskError exception, and we don't want that.
grammatical error, 'raises'

2019-07-29 23:05 UTC, andrey-canon commented on exporter/tasks.py
> +class StudentModuleTask(CourseTask, SQLTask, CopyS3FileTask):
How does it work ?

2019-07-30 00:25 UTC, Squirrel18 commented on exporter/tasks.py
> +    Initially the mongoexport command take the --username and --password parameters,
Addressed.

2019-07-30 00:32 UTC, Squirrel18 commented on exporter/tasks.py
> +            # we don't have data related to the previous run, so
No, it's fine.

2019-07-30 00:32 UTC, Squirrel18 commented on exporter/tasks.py
> +            # this always raise a FatalTaskError exception, and we don't want that.
Addresed.

2019-07-30 00:33 UTC, Squirrel18 commented on exporter/tasks.py
> +class StudentModuleTask(CourseTask, SQLTask, CopyS3FileTask):
Check SQLTask class...

2019-07-30 00:34 UTC, Squirrel18 commented
Check again. @andrey-canon

2019-07-30 15:40 UTC, andrey-canon approved these changes

2019-07-30 21:34 UTC, merged